# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
                ('delivery_deadline', models.DateTimeField(help_text='Please use the following format: <em>YYYY-MM-DD hh:mm</em>')),
                ('demo_deadline', models.DateTimeField(help_text='Please use the following format: <em>YYYY-MM-DD hh:mm</em>')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(help_text='Use upper case letters followed by 4 numbers: Example: TDT4100', max_length=10, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('nickname', models.CharField(blank=True, default='', help_text='Please enter a nickname for the course if possible', max_length=20)),
                ('term', models.CharField(blank=True, help_text='Please use the following format: <season> <year>. Example: Spring 2017', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(help_text='Use upper case letters followed by 4 numbers: Example: TDT4100', max_length=10, unique=True)),
                ('queue', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TAin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TATime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('start_time', models.TimeField(help_text='Please use the following format: <em>hh:mm</em>')),
                ('end_time', models.TimeField(help_text='Please use the following format: <em>hh:mm</em>')),
                ('teaching_assistant', models.CharField(max_length=45)),
                ('room', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
