# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takes',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bota.course.Course'),
        ),
        migrations.AlterField(
            model_name='takes',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bota.course.User'),
        ),
    ]
