# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20170303_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Nickname',
            field=models.CharField(default=b'', help_text=b'Please enter a nickname for the course if possible', max_length=20, null=True),
        ),
    ]
