# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20170221_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Name',
            field=models.CharField(default='TBA', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='Term',
            field=models.CharField(default='TBA', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseID',
            field=models.CharField(max_length=10),
        ),
    ]
