# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20170314_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CourseID',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Nickname',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Term',
            new_name='term',
        ),
        migrations.RenameField(
            model_name='tain',
            old_name='CourseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='tain',
            old_name='UserID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='takes',
            old_name='CourseID',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='takes',
            old_name='UserID',
            new_name='user_id',
        ),
    ]
