# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20170306_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=models.CharField(blank=True, default=b'', max_length=45),
        ),
        migrations.AlterField(
            model_name='course',
            name='Nickname',
            field=models.CharField(blank=True, default=b'', help_text=b'Please enter a nickname for the course if possible', max_length=20),
        ),
    ]
