# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20170324_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(help_text='Use upper case letters followed by 4 numbers: Example: TDT4100', max_length=10, unique=True)),
                ('queue', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
