# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20170309_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
                ('delivery_deadline', models.DateTimeField(help_text=b'Please use the following format: <em>YYYY-MM-DD hh:mm</em>')),
                ('demo_deadline', models.DateTimeField(help_text=b'Please use the following format: <em>YYYY-MM-DD hh:mm</em>')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
    ]
